version: '3.8'
services:
  gateway:
    build: ./gateway
#    image:
#    container_name:
    ports:
      - "8080:8080"
    depends_on:
    - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
#    image:
#    container_name:
    ports:
      - "9090:9090"
    depends_on:
    - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sharedb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  db:
    image: postgres:13.7-alpine
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=sharedb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root