DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS booking CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests (
    id integer generated by default as identity not null PRIMARY KEY,
    description varchar(1024) not null,
    requestor_id integer not null,
    CONSTRAINT fk_requestor_id FOREIGN KEY (requestor_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS items (
    id integer generated by default as identity not null,
    owner_id integer not null,
    name varchar(255) not null,
    description varchar(1024) not null,
    is_available bool not null,
    request_id integer,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_user_id FOREIGN KEY (owner_id) REFERENCES users(id),
    CONSTRAINT fk_requst_id FOREIGN KEY (request_id) REFERENCES requests(id)
);

CREATE TABLE IF NOT EXISTS booking (
    id integer generated by default as identity not null,
    start_date Timestamp WITHOUT TIME ZONE not null,
    end_date Timestamp WITHOUT TIME ZONE not null,
    item_id integer not null,
    booker_id integer not null,
    status varchar(24) not null,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_item_id FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT fk_booker FOREIGN KEY (booker_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS comments (
    id integer generated by default as identity not null,
    text varchar(2048) not null,
    item_id integer not null,
    author_id integer not null,
    created Timestamp WITHOUT TIME ZONE not null,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_item FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT fk_authtor_id FOREIGN KEY (author_id) REFERENCES users(id)
);