CREATE TABLE IF NOT EXISTS users (
    id int GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    id integer generated by default as identity not null,
    user_id integer not null,
    name varchar(255) not null,
    description varchar(1024) not null,
    available bool not null,
    request_id integer,
    CONSTRAINT pk_item PRIMARY KEY (id),
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS item_request (
    id integer generated by default as identity not null,
    description varchar(1024) not null,
    requestor_id integer not null,
    created Timestamp not null,
    CONSTRAINT pk_item_request PRIMARY KEY (id),
    CONSTRAINT fk_requestor_id FOREIGN KEY (requestor_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS booking (
    id integer generated by default as identity not null,
    start_date Timestamp not null,
    end_date Timestamp not null,
    item_id integer not null,
    booker_id integer not null,
    status varchar(24) not null,
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_item_id FOREIGN KEY (item_id) REFERENCES items(id),
    CONSTRAINT fk_booker FOREIGN KEY (booker_id) REFERENCES users(id)
);
